// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MatchMode = ("FIRST" | "ALL")

export interface Roles {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  rule: Rule;
  ruleContext: RuleContext;
  ruleEditorData: RuleEditorData;
  ruleSaveDataArgs: RuleSaveDataArgs;
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface Rule {
  $schema: string;
  config: RuleConfig;
}
export interface RuleConfig {
  data: string;
  decisions: Decision[];
  description: string;
  matchMode: MatchMode;
  name: string;
}
export interface Decision {
  name: string;
  then: Action[];
  when: Condition[];
}
export interface Action {
  field: string;
  value: string;
}
export interface Condition {
  field: string;
  operator: string;
  value: string;
}
export interface RuleContext {
  app: string;
  file: string;
  project: string;
}
export interface RuleEditorData {
  context: RuleContext;
  data: Rule;
  helpUrl: string;
  readonly: boolean;
}
export interface RuleSaveDataArgs {
  context: RuleContext;
  data: Rule;
}
